### ISSUE TITLE
Unable to respond to toots when viewing their URL page

### ISSUE THREAD

**Issue by davidbenque** [hometown-fork/hometown#1147]
### Expected behaviour

When logged in to a Hometown instance and following a link to a toot (e.g. `https://my.instan.ce/@user/123456789`) I should be able to reply to the thread.

### Actual behaviour

I am not able to reply to toots from the URL of a toot, even though I am logged in to a Hometown instance.

### Steps to reproduce the problem

1. Clicking reply on a toot opens a popup with `https://my.instan.ce/interact/123456789?type=reply`
2. I click on "Proceed to reply"
3. The error message "Unfortunately, there was an error looking up the remote account" is displayed, even if the account I am responding to is also on my instance, or if I try to respond to myself.

### Specifications

- Hometown v1.0.5

- Firefox 96.0 (64-bit)
- Ubuntu 20.04

**Comment by dariusk** [comment]
So, this feature works fine for federated posts but I do see the error for local-only posts. This is because technically the feature is a "remote interaction" and remote interactions should fail on local-only posts. I do believe that there should be some kind of detection in place for if you are authorized to see the local-only post but... that is going to be tricky and take a lot of testing. So right now I am going to leave it as is but bookmark this fix for a future version.

**Comment by davidbenque** [comment]
Thank you @dariusk for looking into it!

**Comment by dariusk** [comment]
Note, mostly to myself: this might be fixed by the way Mastodon v4 renders posts now.

**Comment by dariusk** [comment]
Closing this because Mastodon completely changed how replying on someone else's page works (for the worse, I think), and my sense is that there will be a lot of changes coming to this system over time. So I think it would be too much work for me to come up with a fix for this that will likely get blown away by a near-future Mastodon release.
