### ISSUE TITLE
Can't set reply settings in lists

### ISSUE THREAD

**Issue by dariusk** [hometown-fork/hometown#1191]
### Steps to reproduce the problem

1. Go to any list
2. Hit "edit"
3. Attempt to change the "Show replies to"
![image](https://user-images.githubusercontent.com/266454/200649699-6b80e9e2-19fa-4671-afe4-bdc1c1b79f13.png)

### Expected behaviour

It should change

### Actual behaviour

Nothing happens. There is a weird response from the POST request to the API that needs fixin'

### Specifications

Hometown `v1.0.6+3.5.2`

**Comment by johnholdun** [comment]
The controller logic seems fine—there's a log about unpermitted parameters but it's safe to ignore. The issue seems to be in [the arguments sent to `updateList` from `handleRepliesPolicyChange`](https://github.com/hometown-fork/hometown/blob/hometown-dev/app/javascript/mastodon/features/list_timeline/index.js#L140).

I see that you assigned this to yourself already so you might already be working on it, but I didn't realize that until after I packaged up a PR for the fix. Please feel free to ignore if you've got something else!

**Comment by dariusk** [comment]
It's assigned but I'm not active on it! Was planning to do it Friday.
Thanks again for your help
