### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by stemy2** [hometown-fork/hometown#16]
### Expected behaviour

Migrate from my own mastodon instance.

### Actual behaviour

Showing  the error message «fatal: Not a git repository (or any of the parent directories): .git»

### Steps to reproduce the problem

Execute a command from the «initial migration» page.

### Specifications

Commit: Master

**Comment by rscmbbng** [comment]
Can you explain until which step in initial migration you got? Are you sure you changed to the `live` directory of mastodon before executing the commands?

**Comment by stemy2** [comment]
The first. I changed to the live directory and the error is still there.

**Comment by dariusk** [comment]
Hi @stemy2, are you still having this problem? If so, can you tell me how you're running Mastodon? 

For example:

- Are you using Docker?
- Did you install Mastodon from Github or did you unzip a ZIP file?

When you are on your own Mastodon instance and you're in the `~/live` directory, a `git status` command should show you something about git and not the error you reported.

**Comment by stemy2** [comment]
No, i don't use docker.
I installed it from yunohost apps.
A «git status» give me the same message as mentioned above.

**Comment by dariusk** [comment]
Ah. It's probably Yunohost, then. I bet they grab a ZIP of the git repository instead of initializing a local git repo (which makes sense, as Yunohost apps aren't meant to be hacked on and they probably want to save hard drive space).

Sorry I can't help but I'll update the documentation to say that you can't add hometown to Mastodon if installed via Yunohost.
