### ISSUE TITLE
Restrict access to user RSS feeds through authenticated proxy on subscriber's instance

### ISSUE THREAD

**Issue by cadadr** [hometown-fork/hometown#968]
### Pitch

We came up with a potentially useful anti-stalking feature [in a discussion today](https://toot.cat/@cadadr/106307250997123361) and I was told that this for could be receptive of the idea, so I'm posting this suggestion here. I want to say outright that I don't have to know-how to implement a proper patch in reasonable time, so this is purely a feature suggestion. I'm sorry about that. But I'll try my best to promote the suggestion through my fedi account should you deem it worth including.

As you know public posts in Mastodon can be followed without being logged in to your instance, through RSS feeds. This is a neat feature when used responsibly, but it also enables stalkers to work around instance, domain and account blocks. I suggest the following could help make it more difficult for abusers to work around blocks while not making it too hard for legitimate use cases to be realised.

The idea is to make RSS feeds accessible only through an authenticated proxy on the subscriber's instance. If a user A on instance *a* would like to follow a user B on instance *b*, they'd have to access through a URL that looks like follows:

    a.social/feedproxy?account=@B@b.social&key=<auth-token>

This would enforce the following:

- A has to have a mastodon/fediverse account in order to subscribe to B's the RSS feeds
- neither A nor *a* mustn't be blocked by either of B or *b*

A precedent for a mechanism like this is Reddit's [private RSS feeds](https://old.reddit.com/prefs/feeds/) where you can subscribe to your own private activity, e.g. messages you receive, your front page, etc.

This is of course not a full protection, as scraping is still possible, but nevertheless I do believe the two achievements below are worth it:

- it allows to separate undesirable access (x.social/user/feed.rss) from desirable access (through instance proxy), so other security measures like IP bans, rate limiting, etc. could be utilised more easily in a defensive manner
- it makes it less of a low hanging fruit for potential offenders, as they'd need to find or write a scraper, as opposed to just adding a feed url to a feed reader or directly feeding it to bots

Another limitation is of course users on servers that don't implement a `feedproxy` would not be able to access RSS feeds on servers that implement that, but all in all that might be a desirable externality.

I hope I haven't looked over a detail that would make this implausible to implement, and hope the suggestion is welcome. Looking forward to your answers.

I'll also tag glitch-soc maintainers as they too may consider this a worthwile addition: @yipdw @marrus-sh @barzamin (I hope this is not unwelcome and am sorry if it is. In case you want I can reproduce this issue on glitch-soc's tracker separately)

### Motivation

On fediverse we need to hit a balance between making what's public public, and making sure that that publicity does not mean minorities need to be more cautious than majorities with the publicity of their posting, because that sadly goes to silence them. [The upsteam project seems to be disinterested in these matters](https://github.com/tootsuite/mastodon/issues/10221), unlike hometown and glitch-soc, which may consider it worthwile to add the feature. It's sad to encounter fellow fedizens who come out about harassment and stalking they're being subject o on fediverse, and not being able to change the course of the matter because they are not (web) programmers.

---

Hope I was able to clearly articulate the idea. Unfortunately I am not familiar with how ActivityPub or Mastodon works internally, otherwise I'd be able to come up with something more directly actionable implementation-wise. Sorry about that. And thank you so much for maintaining these forks, as someone on a glitch-soc server myself (toot.cat), I'm really grateful for the work of folks like you!

**Comment by marrus-sh** [comment]
Although RSS is what everybody “knows”, public post data is also available without any sort of barrier in JSON-LD form to facilitate certain sorts of “cool things” pertaining to linking federated data on the web—including being able to fetch a post easily when you paste it into the search bar. I don’t think disabling RSS but leaving unauthenticated JSON-LD access is much of a barrier, although it is true that (at present moment) tools for reading RSS are easier to acquire for the technologically unsophisticated. It would be best, I think, if the same solution applied to both.

Because there are desirable reasons to have your information public, especially if you are, say, an organization rather than an individual, this feature would be something to toggle at a user level.

It sounds like what you are asking for is something similar to the ActivityPub secure mode which shipped in Mastodon 3.0. I’m not an expert on secure mode or its implications, but the sense I have gotten is it works on what are essentially similar principles. Of course, secure mode can only be toggled on a server level, and I’m not sure as to its effects on RSS.

So I think “per-user secure mode” might be a good way of phrasing this request, granting the above. The usual warnings apply: More secure means potentially degraded compatibility with older servers, etc. It would be akin to Tumblr’s “make this blog only viewable through the dashboard” preference toggle. I can’t think of why this wouldn’t be possible—but again, I am not an expert in this area.

It’s a much-requested feature, but it’s definitely a big project (maybe not to hack? but to do it right) because at every user endpoint you have to say: Who is requesting this data? Should they have access? What should I tell them if they don’t? And it sounds like you want additional access key generation (for things which aren’t Mastodon servers) as well. You might say that Mastodon should be asking these questions *anyway*—and you would be right! But, well, it mostly isn’t right now.

**Comment by marrus-sh** [comment]
(And of course my comment doesn’t even cover proxying data from other servers, which was the request—but I think locking down the information is the first step. 😜)

**Comment by rkingett** [comment]
How would this work for folks like me that want our RSS feeds basically public and unrestricted? I'm hoping this issue gets some eyeballs, good eyeballs anyway.

Could I still add these proxy feeds to readers? If not, can't instance administrators disable RSS feeds alltogether to protect privacy while leaving RSS open on other instances

**Comment by cadadr** [comment]
> How would this work for folks like me that want our RSS feeds basically public and unrestricted? I'm hoping this issue gets some eyeballs, good eyeballs anyway.

This could be an option in the user settings, something like "Syndication of public toots", with a three-way option of "disabled" which means no RSS feeds, "through feed proxy only" is the way in the issue description (potentially the default), and "unrestricted" which would be how it is now. In the latter case the feed would be available both at `/feedproxy` and at `/users/<nick>.rss` which is the current URL.

> Could I still add these proxy feeds to readers? If not, can't instance administrators disable RSS feeds alltogether to protect privacy while leaving RSS open on other instances

It would work fine. Essentially it'd be an alias URL that enforces authentication through subscriber's own instance. You'd have to treat the token in the proxy url as a secret tho. This is how e.g. private feeds in Reddit work, basically a URL that has an API key somewhere.

@marrus-sh Hmm. That makes the feature sound more complicated than I imagined. Maybe a more plausible step would be to add a two-way toggle for RSS, where it's either enabled as it is or totally disabled, and then more advanced options could be explored.

IDK enough to comment on the rest, unfortunately, besides of course the JSON-LD bit which sounds reasonable, and could maybe be dealt with in a similar step-wise manner (first an option to simply disable, then a way to enable it securely)?

I read about secure mode (i.e. `AUTHORIZED_FETCH`, you mean that, right?) as I researched (admittedly briefly) before posting this issue. Looks like it'd be helpful and feels like it should default to `true`. I also just looked at [this](https://docs.joinmastodon.org/spec/security/) but I'm not sure if what's happening there is authentication or authorisation. If the former, feels like it should be possible to extend that to include RSS. I guess that's what you mean with "per-user secure mode", no? In that case I imagine the whole signature block as a JSON string  could be base64-ified and attached to the request URL, and the subscriber's server would treat it as a JSON-LD request.

I'm sorry if that's some confused gobbledygook, I know nothing about neither Linked Data nor ActivityPub besides knowing their names :disappointed_relieved:

**Comment by dariusk** [comment]
This is a bit complicated for something that is not really within the scope of Hometown. I'm happy to take RSS feature requests based on local-only posting (for example, we don't publish local-only stuff to the RSS feed) but this is seems more of a glitch-soc scoped thing. I would consider pulling the feature in from glitch-soc if it proves to be working and useful for many people once implemented.
